---
- hosts: all
  gather_facts: no
  become: True
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Deploy MetalLB
      include_tasks: ../../tasks/lb/lb-deployment.yaml

