---
- hosts: all
  gather_facts: no
  become: True
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Setup NFS server
      include_tasks: ../../tasks/nfs/nfs-server.yaml

