---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  resources:
    requests:
      memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-main
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30001
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: main
