---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: prometheus-monitoring
  labels:
    volume: nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.150
    path: "/var/nfs/kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prometheus-monitoring
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
