---
- hosts: all
  gather_facts: no
  become: True
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Setup Kubernetes master
      include_tasks: ../../tasks/kubernetes/kubernetes-master.yaml

  handlers:
    - name: docker status
      service: name=docker state=started
